# Generated by Django 4.1 on 2024-08-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yemek", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarifler",
            name="resim",
            field=models.ImageField(upload_to="resimler"),
        ),
    ]
