# Generated by Django 4.1 on 2024-08-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yemek", "0002_alter_tarifler_resim"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarifler",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
