# Generated by Django 4.1 on 2024-08-03 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("yemek", "0005_tarifler_kategori"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarifler",
            name="kategori",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="yemek.kategori",
            ),
        ),
    ]
