# Generated by Django 4.1 on 2024-08-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yemek", "0006_alter_tarifler_kategori"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarifler",
            name="kategori",
        ),
    ]
