# Generated by Django 4.1 on 2024-08-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("yemek", "0007_remove_tarifler_kategori"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarifler",
            name="kategori",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="yemek.kategori",
            ),
        ),
    ]
