# Generated by Django 4.1 on 2024-08-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yemek", "0008_tarifler_kategori"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarifler",
            name="kategori",
        ),
        migrations.AddField(
            model_name="tarifler",
            name="kategori",
            field=models.ManyToManyField(to="yemek.kategori"),
        ),
    ]
