# Generated by Django 4.1 on 2024-08-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yemek", "0009_remove_tarifler_kategori_tarifler_kategori"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("temperature", models.FloatField()),
                ("description", models.CharField(max_length=255)),
                ("icon", models.CharField(max_length=50)),
                ("wind_speed", models.FloatField()),
                ("humidity", models.IntegerField()),
                ("pressure", models.IntegerField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="kategori",
            name="slug",
            field=models.SlugField(blank=True, default="default-slug"),
        ),
        migrations.AlterField(
            model_name="tarifler",
            name="slug",
            field=models.SlugField(blank=True, default="default-slug"),
        ),
    ]
